name: sentinel_rover
description: AI-Powered Laser Sentinel Rover Defense System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.6.1
  geolocator: ^10.1.0
  google_fonts: ^6.2.1
  fl_chart: ^0.66.2
  webview_flutter: ^4.7.0
  flutter_animate: ^4.5.0

  
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  socket_io_client: ^2.0.3+1
  flutter_blue_plus: ^1.32.7
  permission_handler: ^11.0.0




  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
